### ISSUE TITLE
NullPointerException in MockMutablePortletParameters

### ISSUE THREAD

**Issue by XenoGearX** [liferay/portletmvc4spring#5] opened 2020-03-16 11:56 UTC
In the MockMutablePortletParameters class the public String setValue(String name, String value) method triggers a NullPointerException on line 93.

Current code:
`if ((prevValues == null) && (prevValues.length > 0)) {
	return prevValues[0];
}`
Should probably be:
`if ((prevValues != null) && (prevValues.length > 0)) {
	return prevValues[0];
}`

**Comment by ngriffin7a** [comment] 2020-03-25 00:32
@XenoGearX Thanks for creating this issue. I'll investigate as soon as I can. Kind Regards, Neil

**Comment by ngriffin7a** [comment] 2020-03-31 16:52
@XenoGearX I haven't forgotten about this issue. Hope to get to it this week. Thanks for your patience. -- Neil

**Comment by XenoGearX** [comment] 2020-04-01 07:12
@ngriffin7a Thanks for the update

**Comment by ngriffin7a** [comment] 2020-04-13 14:42
@XenoGearX After consulting my schedule, I should be able to spend time on this on Thursday of this week (April 16, 2020).

**Comment by ngriffin7a** [comment] 2020-04-17 19:45
@XenoGearX This issue was fixed moments ago in the following commit:
https://github.com/liferay/portletmvc4spring/commit/9ebfc74041a49039acf65f835d96446355987075

I encountered it myself as I was trying to fix a JUnit failure that I caused by my first attempt at fixing https://issues.liferay.com/browse/MVCS-37

I'll close this GitHub issue, but feel free to comment on MVCS-37 if you have any questions.

Thanks for using PortletMVC4Spring! :)

**Closed as completed** 2020-04-17 19:57 UTC

**Comment by XenoGearX** [comment] 2020-04-20 07:40
@ngriffin7a Hi again, 
the https://issues.liferay.com/browse/MVCS-37 issue points to the SessionState bug. Were both bugs fixed with the same issue?
If not, I don't see any issue regarding this bug in the 5.2.1 release https://issues.liferay.com/browse/MVCS-40?jql=project%20%3D%20MVCS%20AND%20fixVersion%20%3D%205.2.1

Regards,
Safet

**Comment by XenoGearX** [comment] 2020-04-20 07:43
@ngriffin7a My bad, when I checked the commit https://github.com/liferay/portletmvc4spring/commit/9ebfc74041a49039acf65f835d96446355987075, I didn't scroll far enough
